export const ROLE_CONFIG = {
  issuingAuth: [
    "work_hazards",
    "personal_protective_equipment",
    "firefighting_equipment",
    "selected_documents",
    "document_uploads",
    "mechanical_precaution",
    "electrical_precaution",
    "submit",
  ],
  hseAuth: [
    "work_hazards",
    "personal_protective_equipment",
    "firefighting_equipment",
    "selected_documents",
    "document_uploads",
    "mechanical_precaution",
    "electrical_precaution",
    "submit",
  ],
  authorizingAuth: [
    "work_hazards",
    "personal_protective_equipment",
    "firefighting_equipment",
    "selected_documents",
    "document_uploads",
    "mechanical_precaution",
    "electrical_precaution",
    "adjust_time_date",
    "submit",
  ],
  perfAuthSupervisor: ["selected_documents", "document_uploads", "submit"],
  safetyOfficer: ["selected_documents", "document_uploads", "submit"],
  issuingSupervisor: [
    "selected_documents",
    "document_uploads",
    "tool_box_date",
    "submit",
  ],
};
